In [2]:
import numpy as np

In [3]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [4]:
arr4 = np.array([[1.,0.,0.],[0.,1.,2.],[3.,4.,7.],[3.,0.,1.]])
arr4

array([[1., 0., 0.],
       [0., 1., 2.],
       [3., 4., 7.],
       [3., 0., 1.]])

In [5]:
arr4.shape

(4, 3)

# numpy 함수: 수치계산

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
data1 = np.zeros(10)

In [8]:
data1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
data1.dtype

dtype('float64')

In [12]:
data1.shape

(10,)

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

# Array 연산

In [27]:
arr1 = np.array([
                    [1,2,3],
                    [4,5,6]
                ])
arr1.dtype # ndim, shape, dtype

dtype('int32')

In [28]:
arr2 = np.array([
                    [10,11,12],
                    [13,14,15]
                ])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [29]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [30]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [31]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [34]:
arr1 + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [35]:
arr1 - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
arr1 / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [37]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0번째 요소 arr1[0]

In [38]:
arr1[0]

0

In [39]:
arr1[3]

3

3번째 요소부터 8번째 요소 arr1[3:9]

In [40]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

모든 요소의 값

In [41]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr2 = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ])

arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
#3행의 모든 요소 추출하기 → arr2[2:] arr2[행:열]
arr2[2:]

array([[ 9, 10, 11, 12]])

In [45]:
arr2[2:3]

array([[ 9, 10, 11, 12]])

In [48]:
arr2[2,3] # 특정 요소의 값 추출 [,]

12

In [51]:
names = np.array(['홍길동', '박세리', '김병현', '박찬호'])
print(names)

['홍길동' '박세리' '김병현' '박찬호']


In [53]:
names.shape

(4,)

In [54]:
names.ndim

1